### ISSUE TITLE
The RSS gadget is not sending the userId in the request

### ISSUE THREAD

**Issue by voz** [react-epfl/gadget#110]
The gadget: http://graaasp.epfl.ch/gadget/prod/rss/gadget.xml

Graaspeu logs:

``` console
29 Sep 17:51:00 - error: [App] CastError: Cast to ObjectId failed for value "null" at path "_id"
    at ObjectId.cast (/Users/andrii/code/graaspeu/node_modules/mongoose/lib/schema/objectid.js:116:13)
    at ObjectId.castForQuery (/Users/andrii/code/graaspeu/node_modules/mongoose/lib/schema/objectid.js:165:17)
    at Query.cast (/Users/andrii/code/graaspeu/node_modules/mongoose/lib/query.js:2317:32)
    at Query.findOne (/Users/andrii/code/graaspeu/node_modules/mongoose/lib/query.js:1118:10)
    at Query.exec (/Users/andrii/code/graaspeu/node_modules/mongoose/node_modules/mquery/lib/mquery.js:2213:16)
    at Query.exec (/Users/andrii/code/graaspeu/node_modules/mongoose/lib/query.js:1778:19)
    at exports.userById (/Users/andrii/code/graaspeu/app/controllers/users.server.controller.js:30:6)
    at paramCallback (/Users/andrii/code/graaspeu/node_modules/express/lib/router/index.js:378:7)
    at param (/Users/andrii/code/graaspeu/node_modules/express/lib/router/index.js:358:5)
    at Function.proto.process_params (/Users/andrii/code/graaspeu/node_modules/express/lib/router/index.js:384:3)
29 Sep 17:51:00 - info: [Express] GET /users/null?token=ae&userId=5405e1dfda3a95cf9050e5c3 500 78.265 ms - 4212
```

**Comment by MJRodriguezTriana** [comment]
@voz Does the problem appear in both the graasp and the standalone view?
________________________________
